# Generated by Django 4.2.3 on 2023-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(max_length=1000)),
                ('amount', models.IntegerField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(max_length=1000)),
                ('user2_id', models.IntegerField(max_length=1000)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('package_type', models.CharField(max_length=50)),
                ('bought_package', models.BooleanField(default=False)),
                ('account_balance', models.IntegerField(max_length=10)),
                ('referral_balance', models.IntegerField(max_length=10)),
                ('whatsappviews_balance', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(max_length=1000)),
                ('amount', models.IntegerField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
