# Generated by Django 4.2.3 on 2023-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='user2_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsappviews_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
