# Generated by Django 4.2.3 on 2023-07-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_deposit_amount_alter_deposit_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
